import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>daycount</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen">
          <div className="flex justify-end items-center w-2/6 pr-2">
            <span className="text-3xl text-gray-400 whitespace-nowrap">days until</span>
          </div>
          <div className="flex justify-start items-center w-4/6 pl-2">
            <span className="text-3xl underline underline-offset-8 text-blue-400 whitespace-nowrap">24.04.2023</span>
          </div>
      </main>
    </>
  );
};

export default Home;
