import { FC, PropsWithChildren } from "react";
import NavPane from "./navpane";
import Head from "next/head";

const Layout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>daycount</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen">
        <div className="flex w-2/6 items-center justify-end pr-2">
          <NavPane />
        </div>
        <main className="flex w-4/6 items-center justify-start pl-2">
          {children}
        </main>
      </div>
    </>
  );
};

export default Layout;
